'use client';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Plus, Upload, Files, Trash2, Pencil, Check, Copy, Sparkles, Download, ArrowUpRight, X, ExternalLink, FileJson, Eye, ShieldCheck } from 'lucide-react';
import { Empty, Modal, Field, Sources, Tags } from './ui';
import { MAX_PDF_BYTES, parseBatch, makePrompt, exampleBatch, schemas, sourceErrors, weakConcepts, remapLearningSources } from '@/lib/content';
import { inspectPdf } from '@/lib/pdf';
import { uploadMaterial, deleteMaterial, insertRow, updateRow, rpc, downloadJson, materialUrl } from '@/lib/repository';

export function MaterialsPanel(props) {
 const {chapter,materials,scope,data,userId,busy,action,notify,onOpen,preview}=props;
 const [editScope,setEditScope]=useState(null);const [deleting,setDeleting]=useState(null);const [uploading,setUploading]=useState(false);
 async function upload(file){if(!file)return;if(file.size>MAX_PDF_BYTES){notify('每份 PDF 上限為 20 MB，請先壓縮或拆分。',true);return;}if(!file.name.toLowerCase().endsWith('.pdf')){notify('請選擇 PDF 檔案',true);return;}setUploading(true);try{const pages=await inspectPdf(file);await action(()=>uploadMaterial(file,chapter.id,userId,pages),'教材已上傳並完成 PDF 驗證');}catch(e){notify(e.message,true);}finally{setUploading(false);}}
 const visible=materials.filter(m=>m.status!=='deleted');
 const scopes=data.scopes.filter(s=>s.chapter_id===chapter?.id);
 const references=deleting?data.content_items.filter(i=>i.payload.sources?.some(s=>s.materialId===deleting.id)).length:0;
 if(!chapter)return <section className="panel"><Empty title="先建立科目與章節">使用上方「＋科目」與「＋章節」，再保存這個章節的教材。</Empty></section>;
 return <><section className="panel"><div className="section-heading"><div><h2>章節教材</h2><p>每次上傳都建立獨立教材代號，保留原始版本與頁碼。</p></div><label className={`button primary ${uploading||busy?'disabled':''}`}><Upload size={16}/>{uploading?'檢查與上傳中…':'上傳 PDF'}<input className="sr-only" type="file" aria-label="上傳 PDF" accept="application/pdf,.pdf" disabled={busy||uploading||preview} onChange={e=>{const f=e.target.files[0];e.target.value='';upload(f);}}/></label></div>{!visible.length?<div className="upload-empty"><Files size={33}/><h3>把這個章節的教材放進來</h3><p>支援掃描 PDF · 每份上限 20 MB<br/>私人保存，不會自動傳送给 ChatGPT</p></div>:<div className="material-list">{visible.map(m=><div className="material-row" key={m.id}><span className="pdf-icon">PDF</span><div className="material-info"><h3>{m.name}</h3><p>{m.page_count} 頁 · {(m.bytes/1048576).toFixed(1)} MB · {new Date(m.created_at).toLocaleDateString('zh-TW')}</p><small>教材代號：{m.id}</small>{m.status!=='ready'&&<span className="badge warning">{m.status==='delete_pending'?'刪除未完成':'上傳未完成'}</span>}</div><div className="row-actions">{m.status==='ready'&&<><button className="button secondary" onClick={()=>onOpen(m,1)}><Eye size={15}/>閱讀</button><button className="icon-button" title="下載原檔" aria-label={`下載 ${m.name}`} onClick={async()=>{try{window.open(await materialUrl(m),'_blank','noopener,noreferrer');}catch(e){notify(e.message,true);}}}><Download size={17}/></button></>}<button className="icon-button danger" title={m.status==='delete_pending'?'重試刪除':'刪除教材'} aria-label={m.status==='delete_pending'?'重試刪除':'刪除教材'} disabled={busy} onClick={()=>setDeleting(m)}><Trash2 size={17}/></button></div></div>)}</div>}</section>
 <section className="panel"><div className="section-heading"><div><h2>授課與小考範圍</h2><p>使用 PDF 實際頁碼，搭配老師強調與排除的內容。</p></div><button className="button secondary" disabled={!materials.some(m=>m.status==='ready')} onClick={()=>setEditScope({})}><Plus size={16}/>新增範圍</button></div>{!scopes.length?<Empty title="老師目前教到哪裡？">上傳教材後，建立範圍；同一章節可以保存不同週次或考試範圍。</Empty>:<div className="scope-grid">{scopes.map(s=><div className={`scope-card ${s.id===scope?.id?'selected':''}`} key={s.id}><div className="scope-card-head"><h3>{s.name}</h3><span className="badge">版本 {s.revision}</span></div><p>{s.ranges.map(r=>`${materials.find(m=>m.id===r.materialId)?.name||'教材'} · PDF p.${r.pageStart}–${r.pageEnd}`).join('\n')}</p><div className="scope-details"><strong>老師重點</strong><span>{s.teacher_focus||'未指定'}</span><strong>排除內容</strong><span>{s.exclusions||'未指定'}</span></div><button className="text-button" onClick={()=>setEditScope(s)}><Pencil size={14}/>修改範圍</button></div>)}</div>}</section><div className="gentle-note"><ShieldCheck size={19}/><p>範圍變更後會自動檢查題目來源，新教材不會取代舊來源。</p></div>
 {editScope&&<ScopeEditor initial={editScope} {...props} onClose={()=>setEditScope(null)}/>}
 {deleting&&<Modal title="刪除教材" onClose={()=>setDeleting(null)}><p>即將刪除「{deleting.name}」的雲端原檔。</p><div className="callout warning">有 {references} 筆學習內容引用這份教材。刪除後仍保留來源紀錄，但不能閱讀原檔或將相關題目納入新小考。既有小考快照保留。</div><p className="muted">建議先下載一份原檔。若刪除失敗，網站會保留待刪除狀態，方便重試。</p><div className="form-actions"><button className="button secondary" onClick={()=>setDeleting(null)}>取消</button><button className="button danger" disabled={busy} onClick={async()=>{const result=await action(()=>deleteMaterial(deleting),'雲端教材已刪除，來源紀錄保留');if(result)setDeleting(null);else props.refresh?.().catch(()=>{});}}>確認刪除原檔</button></div></Modal>}
 </>;
}

function ScopeEditor({initial,chapter,materials,action,busy,notify,onClose}) {
 const available=materials.filter(m=>m.status==='ready');
 const [name,setName]=useState(initial.name||'');const [focus,setFocus]=useState(initial.teacher_focus||'');const [exclusions,setExclusions]=useState(initial.exclusions||'');
 const [ranges,setRanges]=useState(initial.ranges?.length?initial.ranges:[{materialId:available[0]?.id||'',pageStart:1,pageEnd:available[0]?.page_count||1}]);
 function change(i,k,v){setRanges(rs=>rs.map((r,n)=>n===i?{...r,[k]:v}:r));}
 async function save(e){e.preventDefault();for(const r of ranges){const m=available.find(m=>m.id===r.materialId);if(!m||!Number.isInteger(r.pageStart)||!Number.isInteger(r.pageEnd)||r.pageStart<1||r.pageEnd<r.pageStart||r.pageEnd>m.page_count){notify('請檢查教材與頁碼範圍。',true);return;}}const values={name:name.trim(),ranges,teacher_focus:focus,exclusions};const result=await action(()=>initial.id?updateRow('scopes',initial.id,values):insertRow('scopes',{...values,chapter_id:chapter.id}),initial.id?'範圍已保存':'學習範圍已建立');if(result)onClose();}
 return <Modal title={initial.id?'修改學習範圍':'新增學習範圍'} onClose={onClose} wide><form onSubmit={save}><Field label="範圍名稱"><input required maxLength={100} placeholder="例如：第一週／第一次小考" value={name} onChange={e=>setName(e.target.value)}/></Field><div className="field"><span>教材與 PDF 頁碼</span>{ranges.map((r,i)=><div className="range-row" key={i}><select aria-label={`範圍 ${i+1} 教材`} required value={r.materialId} onChange={e=>change(i,'materialId',e.target.value)}>{!available.some(m=>m.id===r.materialId)&&<option value={r.materialId}>教材不可用，請重新選擇</option>}{available.map(m=><option key={m.id} value={m.id}>{m.name}（{m.page_count} 頁）</option>)}</select><input aria-label={`範圍 ${i+1} 起始頁`} required type="number" min="1" value={r.pageStart} onChange={e=>change(i,'pageStart',Number(e.target.value))}/><span>至</span><input aria-label={`範圍 ${i+1} 結束頁`} required type="number" min="1" value={r.pageEnd} onChange={e=>change(i,'pageEnd',Number(e.target.value))}/><button type="button" className="icon-button" aria-label="移除頁碼區間" disabled={ranges.length===1} onClick={()=>setRanges(rs=>rs.filter((_,n)=>n!==i))}><X size={16}/></button></div>)}<button type="button" className="text-button" disabled={ranges.length>=50} onClick={()=>setRanges(rs=>[...rs,{materialId:available[0]?.id||'',pageStart:1,pageEnd:1}])}>＋增加頁碼區間</button></div><Field label="老師強調的重點"><textarea rows={3} maxLength={20000} value={focus} onChange={e=>setFocus(e.target.value)} placeholder="例如：需要比較的構造、必須理解的概念"/></Field><Field label="排除或尚未教到的內容"><textarea rows={3} maxLength={20000} value={exclusions} onChange={e=>setExclusions(e.target.value)} placeholder="這些內容不應加入本次小考"/></Field>{initial.id&&<div className="callout">變更範圍後會自動檢查來源頁碼；不符合的題目暫不抽入練習。歷史成績不受影響。</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>保存範圍</button></div></form></Modal>;
}

export function NotesPanel(props){
 const {items,materials,onOpen,busy,action}=props;
 const [editor,setEditor]=useState(null);const [filter,setFilter]=useState('all');
 const notes=items.filter(i=>i.kind==='note'&&(filter==='all'||(filter==='excluded'?i.excluded:!i.excluded)));
 return <section className="panel"><div className="section-heading"><div><h2>讓構造與概念連起來</h2><p>保存後即可閱讀，來源頁碼由系統自動檢查。</p></div><button className="button primary" onClick={()=>setEditor({kind:'note'})}><Plus size={16}/>新增筆記</button></div><div className="segmented">{[['all','全部'],['active','使用中'],['excluded','已排除']].map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</div>{!notes.length?<Empty title="從一個概念開始整理">自行新增筆記，或到 ChatGPT 工作區產生提示詞、匯入學習內容。</Empty>:<div className="notes-list">{notes.map(i=><article className="note-card" key={i.id}><div className="note-head"><div><span className={`badge ${i.excluded?'warning':''}`}>{i.excluded?'已排除':'使用中'}</span>{i.payload.supplement&&<span className="badge neutral">補充內容</span>}<h3>{i.payload.title}</h3></div><button className="icon-button" aria-label={`修改 ${i.payload.title}`} onClick={()=>setEditor(i)}><Pencil size={17}/></button></div><Tags concepts={i.payload.concepts}/><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>,img:()=>null}}>{i.payload.markdown}</ReactMarkdown></div><Sources sources={i.payload.sources} materials={materials} onOpen={onOpen}/><button className="text-button" disabled={busy} onClick={()=>action(()=>rpc('set_item_excluded',{p_id:i.id,p_excluded:!i.excluded}),i.excluded?'已恢復筆記':'筆記已排除')}>{i.excluded?'恢復使用':'排除筆記'}</button></article>)}</div>}{editor&&<ContentEditor initial={editor} {...props} onClose={()=>setEditor(null)}/>}</section>;
}

export function ContentEditor({initial,scope,deckId,materials,busy,action,notify,onClose}){
 const kind=initial.kind;const payload=initial.payload||{};
 const [fields,setFields]=useState({...payload,title:payload.title||'',markdown:payload.markdown||'## 核心概念\n\n## 位置與構造\n\n## 功能\n\n## 相互關係\n\n## 易混淆比較\n\n## 自我解釋問題\n',english:payload.english||'',chinese:payload.chinese||'',prompt:payload.prompt||'',explanation:payload.explanation||'',options:payload.options||['','','',''],answerIndex:payload.answerIndex??0,supplement:payload.supplement||false});
 const [concepts,setConcepts]=useState((payload.concepts||[]).join('、'));
 const [sources,setSources]=useState(payload.sources||[]);
 const ready=materials.filter(m=>m.status==='ready');
 const update=(k,v)=>setFields(f=>({...f,[k]:v}));
 async function save(e){e.preventDefault();const common={concepts:concepts.split(/[,，、\n]/).map(s=>s.trim()).filter(Boolean),sources};let value=kind==='note'?{...common,title:fields.title,markdown:fields.markdown,supplement:fields.supplement}:kind==='flashcard'?{...common,english:fields.english,chinese:fields.chinese,explanation:fields.explanation}:{...common,prompt:fields.prompt,options:fields.options,answerIndex:fields.answerIndex,explanation:fields.explanation};const parsed=schemas[kind].safeParse(value);if(!parsed.success){notify(parsed.error.issues.map(i=>`${i.path.join('.')}：${i.message}`).join('\n'),true);return;}value=parsed.data;const errors=sourceErrors(value,kind,scope,materials);if(errors.length){notify(errors.join('\n'),true);return;}const result=await action(()=>kind==='flashcard'?rpc('save_flashcard',{p_deck:deckId||null,p_payload:value,p_id:initial.id||null}):rpc('save_item',{p_scope:scope.id,p_kind:kind,p_payload:value,p_id:initial.id||null}),'內容已保存，可立即使用');if(result)onClose();}
 return <Modal title={`${initial.id?'修改':'新增'}${kind==='note'?'概念筆記':kind==='flashcard'?'單字卡':'單選題'}`} onClose={onClose} wide><form onSubmit={save}>{kind==='note'?<><Field label="筆記標題"><input required value={fields.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="筆記內容（Markdown）"><textarea className="code-input" rows={12} required maxLength={20000} value={fields.markdown} onChange={e=>update('markdown',e.target.value)}/></Field><label className="check-label"><input type="checkbox" checked={fields.supplement} onChange={e=>update('supplement',e.target.checked)}/>補充知識（不作為小考來源）</label></>:kind==='flashcard'?<><Field label="英文"><input required maxLength={300} value={fields.english} onChange={e=>update('english',e.target.value)}/></Field><Field label="中文"><input required value={fields.chinese} onChange={e=>update('chinese',e.target.value)}/></Field><Field label="補充說明"><textarea rows={3} value={fields.explanation} onChange={e=>update('explanation',e.target.value)}/></Field></>:<><Field label="題幹"><textarea rows={3} required value={fields.prompt} onChange={e=>update('prompt',e.target.value)}/></Field><div className="field"><span>四個選項（勾選唯一正解）</span>{fields.options.map((o,i)=><label className="option-edit" key={i}><input aria-label={`設定 ${'ABCD'[i]} 為正解`} type="radio" name="correct-option" checked={fields.answerIndex===i} onChange={()=>update('answerIndex',i)}/><span>{'ABCD'[i]}</span><input aria-label={`選項 ${'ABCD'[i]}`} required value={o} onChange={e=>update('options',fields.options.map((v,n)=>n===i?e.target.value:v))}/></label>)}</div><Field label="答案解析"><textarea required rows={4} value={fields.explanation} onChange={e=>update('explanation',e.target.value)}/></Field></>}
 <Field label="概念標籤" hint="使用頓號或逗號分隔，讓筆記、單字與錯題可以串連。"><input value={concepts} onChange={e=>setConcepts(e.target.value)} placeholder="例如：構造位置、功能比較"/></Field>{kind!=='flashcard'&&<div className="field"><span>來源頁碼{kind==='flashcard'?'（選填）':''}</span>{sources.map((s,i)=><div className="source-edit" key={i}><select aria-label={`來源 ${i+1} 教材`} value={s.materialId} onChange={e=>setSources(ss=>ss.map((v,n)=>n===i?{...v,materialId:e.target.value}:v))}>{!ready.some(m=>m.id===s.materialId)&&<option value={s.materialId}>教材不可用</option>}{ready.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input aria-label={`來源 ${i+1} PDF 頁碼`} type="number" min="1" required value={s.page} onChange={e=>setSources(ss=>ss.map((v,n)=>n===i?{...v,page:Number(e.target.value)}:v))}/><input aria-label={`來源 ${i+1} 書本頁碼`} placeholder="書本頁碼（選填）" maxLength={40} value={s.printedPage||''} onChange={e=>setSources(ss=>ss.map((v,n)=>n===i?{...v,printedPage:e.target.value}:v))}/><button type="button" className="icon-button" aria-label="移除來源" onClick={()=>setSources(ss=>ss.filter((_,n)=>n!==i))}><X size={16}/></button></div>)}<button type="button" className="text-button" disabled={!ready.length||sources.length>=100} onClick={()=>setSources(ss=>[...ss,{materialId:scope.ranges[0]?.materialId||ready[0]?.id,page:scope.ranges[0]?.pageStart||1}])}>＋增加來源</button></div>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>保存內容</button></div></form></Modal>;
}

export function ImportPanel({scope,materials,busy,action,notify,attempts}){
 const [raw,setRaw]=useState('');const [parsed,setParsed]=useState(null);const [batchId,setBatchId]=useState(null);const [weak,setWeak]=useState(false);const [showPrompt,setShowPrompt]=useState(false);const [error,setError]=useState('');const [backup,setBackup]=useState(null);
 const [questionCount,setQuestionCount]=useState(50);
 const prompt=makePrompt(scope,materials,weak?weakConcepts(attempts):[],questionCount);
 const total=parsed?parsed.notes.length+parsed.questions.length:0;
 function change(text){setRaw(text);setParsed(null);setBatchId(null);setError('');}
 function preview(){try{setParsed(parseBatch(raw,scope,materials));setBatchId(crypto.randomUUID());setError('');}catch(e){setError(e.message);setParsed(null);}}
 async function readFile(file){if(!file)return;if(file.size>20*1024*1024){setError('備份檔案上限為 20 MB；學習 JSON 請分批到 2 MB 以內。');return;}try{const text=await file.text();let doc;try{doc=JSON.parse(text);}catch{change(text);return;}if([1,2].includes(doc.backupVersion)){if(!Array.isArray(doc.learningBatches)||!doc.learningBatches.length){setError('備份中沒有可還原的學習內容');return;}setBackup(doc);}else change(text);}catch(e){setError(e.message);}}
 return <><section className="panel"><div className="section-heading"><div><span className="eyebrow">STEP 01 · GENERATE</span><h2>把範圍交給自己的 ChatGPT</h2><p>提示詞會附上教材代號、頁碼、老師重點與 JSON 格式。</p></div><span className="feature-icon"><Sparkles size={23}/></span></div><div className="workflow-steps"><span><b>1</b>複製提示詞</span><Chevron/><span><b>2</b>在 ChatGPT 上傳 PDF</span><Chevron/><span><b>3</b>帶回 JSON</span></div><div className="callout">網站保存 PDF 後，不會自動把檔案傳給 ChatGPT。請在 ChatGPT 另外上傳提示詞列出的教材，並确认檔名與代號對應。</div><label className="check-label"><input type="checkbox" checked={weak} onChange={e=>setWeak(e.target.checked)}/>加入此範圍的弱點概念，請 ChatGPT 產生變化題</label><div className="inline-actions"><button className="button primary" onClick={async()=>{try{await navigator.clipboard.writeText(prompt);notify('提示詞已複製；請到 ChatGPT 上傳教材並貼上。');}catch{setShowPrompt(true);notify('無法自動複製，請從下方文字框手動複製。',true);}}}><Copy size={16}/>複製提示詞</button><button className="button secondary" onClick={()=>setShowPrompt(v=>!v)}><Eye size={16}/>{showPrompt?'收起提示詞':'檢視提示詞'}</button><a className="button ghost" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">開啟 ChatGPT<ExternalLink size={15}/></a></div>{showPrompt&&<textarea aria-label="ChatGPT 提示詞" className="code-input prompt-area" readOnly value={prompt} rows={16}/>}</section>
 <section className="panel"><div className="section-heading"><div><span className="eyebrow">STEP 02 · IMPORT</span><h2>匯入學習內容</h2><p>系統檢查格式與來源，匯入成功即可使用。</p></div><button className="button ghost" onClick={()=>downloadJson('學習內容格式範例.json',exampleBatch(scope))}><Download size={16}/>格式範例</button></div><div className="inline-actions"><label className="button secondary"><FileJson size={16}/>讀取 JSON 或備份<input className="sr-only" aria-label="讀取 JSON" type="file" accept=".json,application/json" onChange={e=>{readFile(e.target.files[0]);e.target.value='';}}/></label><span className="muted">每份上限 2 MB · 每種類最多 300 筆</span></div><Field label="ChatGPT 產題數量"><select value={questionCount} onChange={e=>setQuestionCount(Number(e.target.value))}>{[10,20,30,50,75,100].map(n=><option key={n} value={n}>{n} 題</option>)}</select><small>教材不足時允許減少題目，不硬湊數量。</small></Field><Field label="貼上 ChatGPT 回傳的 JSON"><textarea rows={12} className="code-input" placeholder={'{\n  "schemaVersion": 2,\n  "notes": [],\n  "questions": []\n}'} value={raw} onChange={e=>change(e.target.value)}/></Field>{error&&<pre className="import-error" role="alert">{error}</pre>}<button className="button secondary" disabled={!raw.trim()} onClick={preview}><Eye size={16}/>驗證並預覽</button>
 {parsed&&<div className="import-preview">{parsed.ignoredFlashcards>0&&<p className="callout">舊格式含 {parsed.ignoredFlashcards} 張單字卡，本次不匯入單字。請自行新增，或從學習備份還原至單字庫。</p>}<div className="preview-summary"><Check size={20}/><strong>格式及來源範圍檢查通過</strong><span>{parsed.notes.length} 篇筆記 · {parsed.questions.length} 道題目</span></div><p className="muted">這只代表格式與頁碼有效，不代表 AI 內容正確。以下 {total} 筆匯入後立即可用。</p>{[['notes','筆記'],['questions','題目']].map(([key,label])=><div key={key}>{parsed[key].map((p,i)=><details key={i}><summary>{label} {i+1} · {p.title||p.english||p.prompt}</summary><pre>{JSON.stringify(p,null,2)}</pre></details>)}</div>)}<div className="form-actions"><button className="button primary" disabled={busy} onClick={async()=>{const result=await action(()=>rpc('import_content',{p_scope:scope.id,p_revision:scope.revision,p_batch:batchId,p_payload:{schemaVersion:2,notes:parsed.notes,questions:parsed.questions}}),'內容已匯入，可立即使用');if(result){change('');}}}><Upload size={16}/>確認匯入 {total} 筆內容</button></div></div>}
 </section>{backup&&<BackupImporter backup={backup} scope={scope} materials={materials} notify={notify} onClose={()=>setBackup(null)} onPrepare={text=>{change(text);setBackup(null);}}/>}</>;
}
function Chevron(){return <ArrowUpRight className="workflow-arrow" size={14}/>;}

function BackupImporter({backup,scope,materials,notify,onClose,onPrepare}){
 const [selected,setSelected]=useState(Math.max(0,backup.learningBatches.findIndex(b=>b.scopeId===scope.id)));const [mapping,setMapping]=useState({});
 const entry=backup.learningBatches[selected];const payload=entry.payload;
 const ids=[...new Set(['notes','questions'].flatMap(k=>(payload[k]||[]).flatMap(i=>(i.sources||[]).map(s=>s.materialId))))];
 const ready=materials.filter(m=>m.status==='ready');
 const effective=Object.fromEntries(ids.map(id=>[id,mapping[id]||(ready.some(m=>m.id===id)?id:'')]));
 return <Modal title="從備份準備學習內容" onClose={onClose} wide><Field label="備份中的學習範圍"><select value={selected} onChange={e=>{setSelected(Number(e.target.value));setMapping({});}}>{backup.learningBatches.map((b,i)=><option key={i} value={i}>{b.scopeName||b.scopeId}</option>)}</select></Field><div className="callout">匯入目標：{scope.name}。這裡還原筆記與題目，保存後即可使用；單字請到單字庫還原；歷史小考與熟悉程度保留在備份中，不覆寫目前紀錄。PDF 請先另外上傳。</div>{ids.map(id=><Field key={id} label={`原教材：${backup.materials?.find(m=>m.id===id)?.name||id}`} hint={`原代號：${id}`}><select required value={effective[id]} onChange={e=>setMapping(m=>({...m,[id]:e.target.value}))}><option value="">請明確選擇對應教材</option>{ready.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>)}<p className="muted">來源頁碼會保留原數字。教材版本或掃描順序不同時，請在預覽 JSON 中修正頁碼，再確認頁碼。</p><div className="form-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" onClick={()=>{try{onPrepare(JSON.stringify(remapLearningSources({schemaVersion:2,notes:payload.notes||[],questions:payload.questions||[]},effective),null,2));}catch(e){notify(e.message,true);}}}>帶入 JSON，重新驗證</button></div></Modal>;
}
