// Runs the real migration in an in-memory PostgreSQL engine. It cannot contact your Supabase project.
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
await db.exec(`create role anon; create role authenticated;
create schema auth; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant usage on schema storage to authenticated,anon;
grant all on storage.objects to authenticated; grant select on storage.objects to anon;
create function storage.foldername(text) returns text[] language sql immutable as $$ select string_to_array($1,'/') $$;`);
await db.exec(await readFile('supabase/migrations/001_study.sql','utf8'));
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
await db.query('insert into auth.users values ($1),($2)',[a,b]);
async function asUser(user,sql,params=[]){await db.exec(`reset role; set request.jwt.claim.sub='${user||''}'; set role ${user?'authenticated':'anon'};`);try{return (await db.query(sql,params)).rows;}finally{await db.exec('reset role');}}
async function reject(user,sql,params=[]){let rejected=false;try{await asUser(user,sql,params);}catch{rejected=true;}assert.ok(rejected,`Must reject: ${sql}`);checks++;}
function check(condition,label){assert.ok(condition,label);checks++;console.log(`✓ ${label}`);}
const [subject]=await asUser(a,"insert into public.subjects(name) values ('解剖學') returning *");
const [chapter]=await asUser(a,"insert into public.chapters(subject_id,name) values ($1,'骨骼系統') returning *",[subject.id]);
const mid='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const [material]=await asUser(a,"insert into public.materials(id,chapter_id,name,storage_path,bytes,page_count) values ($1,$2,'chapter.pdf',$3,100,10) returning *",[mid,chapter.id,`${a}/${mid}.pdf`]);
await asUser(a,"insert into storage.objects(bucket_id,name) values ('study-materials',$1)",[material.storage_path]);
await asUser(a,"update public.materials set status='ready' where id=$1",[mid]);
const [scope]=await asUser(a,"insert into public.scopes(chapter_id,name,ranges) values ($1,'本週',$2) returning *",[chapter.id,JSON.stringify([{materialId:mid,pageStart:1,pageEnd:4}])]);
check((await asUser(b,'select * from public.subjects')).length===0,'Other account cannot read rows');
check((await asUser(b,'select * from storage.objects')).length===0,'Other account cannot read PDF objects');
check((await asUser(null,'select * from storage.objects')).length===0,'Anonymous cannot read PDF objects');
await reject(null,'select * from public.subjects');
await reject(b,"insert into public.chapters(subject_id,name) values ($1,'foreign')",[subject.id]);
await reject(b,"insert into storage.objects(bucket_id,name) values ('study-materials',$1)",[`${a}/spoof.pdf`]);
await asUser(a,"update storage.objects set name='replace.pdf' where name=$1",[material.storage_path]);
check((await asUser(a,'select * from storage.objects'))[0].name===material.storage_path,'PDF objects cannot be overwritten');
await reject(a,"insert into public.scopes(chapter_id,name,ranges) values ($1,'bad',$2)",[chapter.id,JSON.stringify([{materialId:mid,pageStart:1,pageEnd:11}])]);
const sources=[{materialId:mid,page:2}];
const note={title:'概念',markdown:'核對筆記',supplement:false,concepts:['位置'],sources};
const card={english:'term',chinese:'名稱',explanation:'說明',concepts:['位置'],sources};
const question={prompt:'題幹',options:['a','b','c','d'],answerIndex:0,explanation:'原解析',concepts:['位置'],sources};
const batch={schemaVersion:1,notes:[note],flashcards:[card],questions:[question]};
const bid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
await reject(a,'select public.import_content($1,null,$2,$3)',[scope.id,bid,JSON.stringify(batch)]);
await reject(a,'select public.import_content($1,1,$2,$3)',[scope.id,bid,JSON.stringify({...batch,questions:[{...question,answerIndex:7}]})]);
check((await asUser(a,'select * from public.content_items')).length===0,'Invalid batch rolls back all content');
check((await asUser(a,'select * from public.import_batches')).length===0,'Invalid batch rolls back batch registration');
await asUser(a,'select public.import_content($1,1,$2,$3)',[scope.id,bid,JSON.stringify(batch)]);
await reject(a,'select public.import_content($1,1,$2,$3)',[scope.id,bid,JSON.stringify(batch)]);
await reject(a,'select public.import_content($1,1,gen_random_uuid(),$2)',[scope.id,JSON.stringify(batch)]);
await reject(a,'select public.import_content($1,1,gen_random_uuid(),$2)',[scope.id,JSON.stringify({schemaVersion:1,questions:[{...question,sources:[{materialId:mid,page:5}]}]})]);
check((await asUser(a,'select * from public.content_items')).length===3,'Valid import inserts all three kinds, replay rejected');
const items=await asUser(a,'select * from public.content_items');const qi=items.find(i=>i.kind==='question'),ci=items.find(i=>i.kind==='flashcard');
await reject(a,'select public.start_quiz($1,10,false)',[scope.id]);
await reject(a,"insert into public.content_items(scope_id,kind,payload,reviewed) values ($1,'question',$2,true)",[scope.id,JSON.stringify(question)]);
await reject(a,'select public.assert_payload($1,$2,$3,$4)',['question',JSON.stringify(question),scope.id,a]);
await reject(b,'select public.review_item($1,1,$2,false)',[qi.id,JSON.stringify(question)]);
await reject(a,'select public.review_item($1,null,$2,false)',[qi.id,JSON.stringify(question)]);
await asUser(a,'select public.review_item($1,1,$2,false)',[qi.id,JSON.stringify(question)]);
await asUser(a,'select public.review_item($1,1,$2,false)',[ci.id,JSON.stringify(card)]);
await asUser(a,"select public.set_card_progress($1,'familiar')",[ci.id]);
await reject(b,"select public.set_card_progress($1,'familiar')",[ci.id]);
const [started]=await asUser(a,'select * from public.start_quiz($1,10,false)',[scope.id]);
check(started.snapshot.length===1,'Only reviewed questions included; shortage uses actual count');
await reject(b,'select * from public.submit_quiz($1,$2)',[started.id,JSON.stringify([{choice:0,uncertain:false}])]);
await reject(a,'select * from public.submit_quiz($1,$2)',[started.id,'[]']);
const [graded]=await asUser(a,'select * from public.submit_quiz($1,$2)',[started.id,JSON.stringify([{choice:0,uncertain:true}])]);
check(graded.score===1&&graded.results[0].uncertain,'Server grades correctly and retains confidence');
const [regraded]=await asUser(a,'select * from public.submit_quiz($1,$2)',[started.id,JSON.stringify([{choice:3,uncertain:false}])]);
check(regraded.score===1,'Duplicate submission cannot change saved score');
const [weakQuiz]=await asUser(a,'select * from public.start_quiz($1,10,true)',[scope.id]);
check(weakQuiz.snapshot.length===1,'Correct but uncertain answers enter weak practice');
const [related]=await asUser(a,'select public.save_item($1,$2,$3,null) as id',[scope.id,'question',JSON.stringify({...question,prompt:'同概念變化題'})]);
await asUser(a,'select public.review_item($1,1,$2,false)',[related.id,JSON.stringify({...question,prompt:'同概念變化題'})]);
const [relatedQuiz]=await asUser(a,'select * from public.start_quiz($1,10,true)',[scope.id]);
check(relatedQuiz.snapshot.length===2,'Weak practice also includes reviewed questions sharing weak concepts');
await asUser(a,'select public.save_item($1,$2,$3,$4)',[scope.id,'question',JSON.stringify({...question,explanation:'新解析',answerIndex:1}),qi.id]);
const [oldResult]=await asUser(a,'select * from public.quiz_attempts where id=$1',[started.id]);
check(oldResult.results[0].payload.explanation==='原解析'&&oldResult.results[0].payload.answerIndex===0,'History snapshots survive question edits');
await reject(a,'select public.review_item($1,1,$2,false)',[qi.id,JSON.stringify(question)]);
await asUser(a,'select public.review_item($1,1,$2,false)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await asUser(a,"update public.scopes set exclusions='新排除內容' where id=$1",[scope.id]);
check((await asUser(a,'select * from public.content_items where reviewed')).length===0,'Scope change invalidates all reviews');
await reject(a,'select public.review_item($1,1,$2,false)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await reject(a,'select public.start_quiz($1,10,false)',[scope.id]);
await asUser(a,'select public.review_item($1,2,$2,false)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await asUser(a,'select public.review_item($1,2,$2,true)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await reject(a,'select public.start_quiz($1,10,false)',[scope.id]);
await asUser(a,'select public.review_item($1,2,$2,false)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await asUser(a,"update public.materials set status='delete_pending' where id=$1",[mid]);
check((await asUser(a,'select * from public.content_items where reviewed')).length===0,'Deleting material invalidates affected reviews');
check((await asUser(b,'select * from storage.objects')).length===0,'Pending delete PDF stays private');
await asUser(a,'delete from storage.objects where name=$1',[material.storage_path]);
check((await db.query('select * from storage.objects')).rows.length===0,'Pending deletion actually removes Storage object');
await asUser(a,"update public.materials set status='deleted' where id=$1",[mid]);
await reject(a,'select public.review_item($1,2,$2,false)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
await asUser(a,'select public.review_item($1,2,$2,true)',[qi.id,JSON.stringify({...question,explanation:'新解析',answerIndex:1})]);
check((await asUser(a,'select * from public.quiz_attempts where id=$1',[started.id]))[0].score===1,'Material deletion preserves historic grades');
console.log(`\n${checks} database checks passed (in-memory PostgreSQL; not a live Supabase test).`);
await db.close();
